trigger:
- master

pool: SelfHosted_Akash

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run android-browserstack
  displayName: 'npm install and build'